#### 1. Import the numpy package under the name `np`

In [2]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  How to get the documentation of the numpy add function? 

In [4]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

In [5]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 5.  Create a numpy array with values ranging from 10 to 49

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

In [7]:
np.arange(51)[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

In [8]:
a = np.arange(9)
a.shape = (3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [9]:
a = np.array([1,2,0,0,4,0])
res = np.where(a!=0)
res

(array([0, 1, 4]),)

#### 9. Create a 3x3x3 array with random integers from 1 to 20

In [10]:
np.random.randint(1, 20, (3,3,3))

array([[[15, 11, 12],
        [12, 16, 15],
        [13, 17, 14]],

       [[18, 10, 14],
        [14, 16,  2],
        [14, 17,  8]],

       [[ 8,  6,  6],
        [ 5,  2,  5],
        [15, 13,  6]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

In [11]:
r = np.random.random((10,10))
rmin, rmax = r.min(), r.max()
print(rmin, rmax)

0.006046516341544739 0.986960430337516


#### 11. Create a random vector of size 30 and find the mean value 

In [12]:
m = np.random.random(30)
print(m.mean())

0.4357770636283878


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

In [13]:
arr = np.arange(0, 11)  
print('original array',arr)
res = np.where((arr >= 3) & (arr <= 8))
new_arr = arr[res]
print('modified array',new_arr)

original array [ 0  1  2  3  4  5  6  7  8  9 10]
modified array [3 4 5 6 7 8]


#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

In [14]:
b = np.random.randint(1, 10, 20)
print('original array',b)
inds = np.where(b < 5)
type(inds)
for ind in inds:
    b[ind] = b[ind] * 2
print('modified array', b)

original array [3 2 8 2 8 9 9 4 7 6 5 3 8 2 5 9 3 6 2 7]
modified array [6 4 8 4 8 9 9 8 7 6 5 6 8 4 5 9 6 6 4 7]


#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

In [15]:
c = np.array([1, 5, 6, 2, -2, 23, 45])
res_c = np.where(c % 2 == 0)
res_c[0]

array([2, 3, 4])

#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

In [16]:
d = np.arange(0,21)
print(d)
d[np.where(d % 3 == 0)]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 0,  3,  6,  9, 12, 15, 18])

#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

In [17]:
e = np.arange(0,5)
np.tile(e,5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 17. Create a 3x5 numpy array filled with random numbers from 1 to 10.

In [18]:
np.random.randint(1,10, (3,5))

array([[8, 5, 8, 5, 3],
       [5, 5, 4, 3, 1],
       [8, 3, 5, 9, 8]])

#### 18. Create a numpy array of size 10 filled with 0s and replace its 5th value with a 3.

In [19]:
g = np.zeros(10)
g[4] = 3
print(g)

[0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]


#### 19. Create a numpy array filled with numbers from 3 to 15 i.e. ([3, 4 … 13, 14])

In [20]:
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 20. Write a function which gets a numpy array as an input and divides all of the array values by 2 over and over again, until the mean of the array numbers is <=5. Then, once the mean of the array numbers is <=5, the funtion returns the modified numpy array. 

In [21]:
def div_by_two(arr):
    while np.mean(arr) > 5:
        arr = np.divide(arr,2)
    return arr

In [22]:
div_by_two(np.array([10,14,20,11,9]))

array([2.5 , 3.5 , 5.  , 2.75, 2.25])

#### 21. Write a function which gets a 5x4 numpy array filled with random numbers from 1 to 10 as an inputand returns 4 different numpy arrays which are the columns of the original numpy array. Write another similar function which returns 5 different numpy arrays which are rows of the original numpy array. 

In [23]:
def get_cols(arr):
    c0 = arr[:,0]
    c1 = arr[:,1]
    c2 = arr[:,2]
    c3 = arr[:,3]
    return c0, c1, c2, c3 

def get_rows(arr):
    r0 = arr[0]
    r1 = arr[1]
    r2 = arr[2]
    r3 = arr[3]
    r4 = arr[4]
    return r0, r1, r2, r3, r4

In [26]:
m = np.random.randint(1,10,(5,4))
print('original matrix:', z)
print('extracted cols: ', get_cols(m))
print('extracted rows: ', get_rows(m))

original matrix: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
extracted cols:  (array([8, 4, 5, 4, 9]), array([4, 2, 4, 1, 9]), array([4, 8, 2, 4, 3]), array([4, 1, 1, 5, 4]))
extracted rows:  (array([8, 4, 4, 4]), array([4, 2, 8, 1]), array([5, 4, 2, 1]), array([4, 1, 4, 5]), array([9, 9, 3, 4]))
